### ISSUE TITLE
Unable to run `rails db:create`

### ISSUE THREAD

**Issue by ryanb** [wallaby-rails/wallaby-rails#170]
I attempted to run `rails db:create` on the [demo app](https://github.com/tian-im/wallaby_demo) and it failed with the following:

```
ActiveRecord::NoDatabaseError: FATAL:  database "wallaby_demo_development" does not exist
/Users/rbates/code/gh/wallaby_demo/app/decorators/product_decorator.rb:2:in `<class:ProductDecorator>'
/Users/rbates/code/gh/wallaby_demo/app/decorators/product_decorator.rb:1:in `<top (required)>'
/Users/rbates/code/gh/wallaby_demo/config/environment.rb:5:in `<top (required)>'
```

I believe this is because decorators depend on the database existing before the class will load. Perhaps check if the database exists before attempting to use it.

**Comment by tian-im** [comment]
Yep, looking into this one.

**Comment by tian-im** [comment]
Done. It's in the master now

**Comment by tian-im** [comment]
@ryanb see this release https://github.com/wallaby-rails/wallaby-active_record/releases/tag/0.2.2

please try to upgrade `wallaby-active_record` to `0.2.2` and let me know if it works for you or not.

**Comment by ryanb** [comment]
Thanks! I tried it out on the demo app and it works. Closing.

**Comment by ryanb** [comment]
I think this issue is back again with the 6.1.2. I'm getting this stack trace when running `rake db:setup`

```
NoMethodError: undefined method `[]=' for nil:NilClass
521/home/travis/build/exec-io/envisage/app/decorators/support_admin/account_decorator.rb:5:in `<class:AccountDecorator>'
522/home/travis/build/exec-io/envisage/app/decorators/support_admin/account_decorator.rb:1:in `<top (required)>'
523/home/travis/build/exec-io/envisage/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
524/home/travis/build/exec-io/envisage/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
525/home/travis/build/exec-io/envisage/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
526/home/travis/build/exec-io/envisage/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
527/home/travis/build/exec-io/envisage/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
528/home/travis/build/exec-io/envisage/vendor/bundle/ruby/2.5.0/gems/skylight-core-4.2.3/lib/skylight/core/probes.rb:118:in `require'
529/home/travis/build/exec-io/envisage/vendor/bundle/ruby/2.5.0/gems/zeitwerk-2.3.0/lib/zeitwerk/kernel.rb:16:in `require'
530/home/travis/build/exec-io/envisage/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.2.2/lib/active_support/dependencies/zeitwerk_integration.rb:49:in `require_dependency'
531/home/travis/build/exec-io/envisage/vendor/bundle/ruby/2.5.0/gems/wallaby-core-0.2.2/lib/wallaby/preloader.rb:17:in `each'
532/home/travis/build/exec-io/envisage/vendor/bundle/ruby/2.5.0/gems/wallaby-core-0.2.2/lib/wallaby/preloader.rb:17:in `require_all'
533/home/travis/build/exec-io/envisage/vendor/bundle/ruby/2.5.0/gems/wallaby-core-0.2.2/lib/wallaby/engine.rb:28:in `block in <class:Engine>'
534/home/travis/build/exec-io/envisage/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.2.2/lib/active_support/lazy_load_hooks.rb:69:in `block in execute_hook'
535/home/travis/build/exec-io/envisage/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.2.2/lib/active_support/lazy_load_hooks.rb:62:in `with_execution_control'
536/home/travis/build/exec-io/envisage/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.2.2/lib/active_support/lazy_load_hooks.rb:67:in `execute_hook'
537/home/travis/build/exec-io/envisage/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.2.2/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
538/home/travis/build/exec-io/envisage/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.2.2/lib/active_support/lazy_load_hooks.rb:51:in `each'
539/home/travis/build/exec-io/envisage/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.2.2/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
540/home/travis/build/exec-io/envisage/vendor/bundle/ruby/2.5.0/gems/railties-6.0.2.2/lib/rails/application/finisher.rb:129:in `block in <module:Finisher>'
541/home/travis/build/exec-io/envisage/vendor/bundle/ruby/2.5.0/gems/railties-6.0.2.2/lib/rails/initializable.rb:32:in `instance_exec'
542/home/travis/build/exec-io/envisage/vendor/bundle/ruby/2.5.0/gems/railties-6.0.2.2/lib/rails/initializable.rb:32:in `run'
543/home/travis/build/exec-io/envisage/vendor/bundle/ruby/2.5.0/gems/railties-6.0.2.2/lib/rails/initializable.rb:61:in `block in run_initializers'
544/home/travis/build/exec-io/envisage/vendor/bundle/ruby/2.5.0/gems/railties-6.0.2.2/lib/rails/initializable.rb:60:in `run_initializers'
545/home/travis/build/exec-io/envisage/vendor/bundle/ruby/2.5.0/gems/railties-6.0.2.2/lib/rails/application.rb:363:in `initialize!'
546/home/travis/build/exec-io/envisage/config/environment.rb:5:in `<top (required)>'
...
```

Looks like Wallaby is loading the decorators before the tables exist which causes this error.

**Comment by tian-im** [comment]
I think this is caused by the this line:

```
self.index_fields[:referrer_account][:label] = 'Referrer'
```

and `self.index_fields[:referrer_account]` is nil when database is not there.

But it seems like this line is there for a while, how come it wasn't complaining in the latest version. Will fix it by making `self.index_fields[:referrer_account]` to return an empty hash

**Comment by tian-im** [comment]
@ryanb could you update to wallaby 6.1.3 and see if it is ok for you?

**Comment by ryanb** [comment]
@tian-im looks like this is working, thanks!

**Comment by ryanb** [comment]
@tian-im this issue is back in Wallaby 6.1.5. I'm seeing `NoMethodError: undefined method `[]=' for nil:NilClass` on line 5.

```rb
class SupportAdmin::AccountDecorator < SupportAdmin::ApplicationDecorator
  self.index_field_names = ['id', 'token', 'name', 'account_email', 'status', 'referrer_account', 'referral_id']
  self.index_fields[:account_email] = { type: 'email', label: 'email' }
  # Note, if you get an error here on specs, reset your database
  self.index_fields[:referrer_account][:label] = 'Referrer'
  self.index_fields[:status] = { type: 'string' }
  # ...
end
```

Any ideas? Can we move this setting outside the class loading so it allows creating the database?

**Comment by tian-im** [comment]
@ryanb I think the root cause is related to the previous clone, Hash's [`default` value](https://ruby-doc.org/core-2.7.2/Hash.html#default-method) is not cloned using the new way. Will fix this now.

**Comment by tian-im** [comment]
@ryanb I've published the fix in `wallaby-core(0.2.5)`, could you do an update and see if it is fixed?

**Comment by tian-im** [comment]
@ryanb does the latest release work for you? Let me know if it doesn't. I will take another look

**Comment by ryanb** [comment]
@tian-im I believe that fixed it, thanks Tian!

**Comment by ryanb** [comment]
@tian-im sorry, false alarm. Travis CI is showing the same error with wallaby-core 0.2.5.

**Comment by tian-im** [comment]
@ryanb do you have the error stack trace if possible?

**Comment by ryanb** [comment]
@tian-im here it is.

```
== Preparing database ==
2022-03-09T17:47:14.676Z pid=8738 tid=2lm INFO: Booting Sidekiq 6.4.1 with redis options {:url=>nil, :db=>1}
rails aborted!
NoMethodError: undefined method `[]=' for nil:NilClass
/home/travis/build/exec-io/envisage/app/decorators/support_admin/account_decorator.rb:5:in `<class:AccountDecorator>'
/home/travis/build/exec-io/envisage/app/decorators/support_admin/account_decorator.rb:1:in `<main>'
/home/travis/build/exec-io/envisage/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/home/travis/build/exec-io/envisage/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/home/travis/build/exec-io/envisage/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:27:in `require'
/home/travis/build/exec-io/envisage/vendor/bundle/ruby/2.7.0/gems/skylight-5.3.1/lib/skylight/probes.rb:167:in `require'
/home/travis/build/exec-io/envisage/vendor/bundle/ruby/2.7.0/gems/activesupport-7.0.0/lib/active_support/dependencies/require_dependency.rb:21:in `require_dependency'
/home/travis/build/exec-io/envisage/vendor/bundle/ruby/2.7.0/gems/wallaby-core-0.2.5/lib/wallaby/preloader.rb:17:in `each'
/home/travis/build/exec-io/envisage/vendor/bundle/ruby/2.7.0/gems/wallaby-core-0.2.5/lib/wallaby/preloader.rb:17:in `require_all'
/home/travis/build/exec-io/envisage/vendor/bundle/ruby/2.7.0/gems/wallaby-core-0.2.5/lib/wallaby/engine.rb:28:in `block in <class:Engine>'
/home/travis/build/exec-io/envisage/vendor/bundle/ruby/2.7.0/gems/activesupport-7.0.0/lib/active_support/lazy_load_hooks.rb:68:in `block in execute_hook'
/home/travis/build/exec-io/envisage/vendor/bundle/ruby/2.7.0/gems/activesupport-7.0.0/lib/active_support/lazy_load_hooks.rb:61:in `with_execution_control'
/home/travis/build/exec-io/envisage/vendor/bundle/ruby/2.7.0/gems/activesupport-7.0.0/lib/active_support/lazy_load_hooks.rb:66:in `execute_hook'
/home/travis/build/exec-io/envisage/vendor/bundle/ruby/2.7.0/gems/activesupport-7.0.0/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
/home/travis/build/exec-io/envisage/vendor/bundle/ruby/2.7.0/gems/activesupport-7.0.0/lib/active_support/lazy_load_hooks.rb:51:in `each'
/home/travis/build/exec-io/envisage/vendor/bundle/ruby/2.7.0/gems/activesupport-7.0.0/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
/home/travis/build/exec-io/envisage/vendor/bundle/ruby/2.7.0/gems/railties-7.0.0/lib/rails/application/finisher.rb:86:in `block in <module:Finisher>'
/home/travis/build/exec-io/envisage/vendor/bundle/ruby/2.7.0/gems/railties-7.0.0/lib/rails/initializable.rb:32:in `instance_exec'
/home/travis/build/exec-io/envisage/vendor/bundle/ruby/2.7.0/gems/railties-7.0.0/lib/rails/initializable.rb:32:in `run'
/home/travis/build/exec-io/envisage/vendor/bundle/ruby/2.7.0/gems/railties-7.0.0/lib/rails/initializable.rb:61:in `block in run_initializers'
/home/travis/build/exec-io/envisage/vendor/bundle/ruby/2.7.0/gems/railties-7.0.0/lib/rails/initializable.rb:60:in `run_initializers'
/home/travis/build/exec-io/envisage/vendor/bundle/ruby/2.7.0/gems/railties-7.0.0/lib/rails/application.rb:369:in `initialize!'
/home/travis/build/exec-io/envisage/config/environment.rb:5:in `<main>'
/home/travis/build/exec-io/envisage/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/home/travis/build/exec-io/envisage/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/home/travis/build/exec-io/envisage/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
/home/travis/build/exec-io/envisage/vendor/bundle/ruby/2.7.0/gems/skylight-5.3.1/lib/skylight/probes.rb:167:in `require'
/home/travis/build/exec-io/envisage/vendor/bundle/ruby/2.7.0/gems/railties-7.0.0/lib/rails/application.rb:345:in `require_environment!'
/home/travis/build/exec-io/envisage/vendor/bundle/ruby/2.7.0/gems/railties-7.0.0/lib/rails/application.rb:507:in `block in run_tasks_blocks'
/home/travis/build/exec-io/envisage/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `block in execute'
/home/travis/build/exec-io/envisage/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `each'
/home/travis/build/exec-io/envisage/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `execute'
/home/travis/build/exec-io/envisage/vendor/bundle/ruby/2.7.0/gems/bugsnag-6.24.2/lib/bugsnag/integrations/rake.rb:20:in `execute'
/home/travis/build/exec-io/envisage/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/home/travis/build/exec-io/envisage/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
/home/travis/build/exec-io/envisage/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
/home/travis/build/exec-io/envisage/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:243:in `block in invoke_prerequisites'
/home/travis/build/exec-io/envisage/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:241:in `each'
/home/travis/build/exec-io/envisage/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:241:in `invoke_prerequisites'
/home/travis/build/exec-io/envisage/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:218:in `block in invoke_with_call_chain'
/home/travis/build/exec-io/envisage/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
/home/travis/build/exec-io/envisage/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
/home/travis/build/exec-io/envisage/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:243:in `block in invoke_prerequisites'
/home/travis/build/exec-io/envisage/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:241:in `each'
/home/travis/build/exec-io/envisage/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:241:in `invoke_prerequisites'
/home/travis/build/exec-io/envisage/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:218:in `block in invoke_with_call_chain'
/home/travis/build/exec-io/envisage/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
/home/travis/build/exec-io/envisage/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
/home/travis/build/exec-io/envisage/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:188:in `invoke'
/home/travis/build/exec-io/envisage/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:160:in `invoke_task'
/home/travis/build/exec-io/envisage/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/home/travis/build/exec-io/envisage/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `each'
/home/travis/build/exec-io/envisage/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block in top_level'
/home/travis/build/exec-io/envisage/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:125:in `run_with_threads'
/home/travis/build/exec-io/envisage/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:110:in `top_level'
/home/travis/build/exec-io/envisage/vendor/bundle/ruby/2.7.0/gems/railties-7.0.0/lib/rails/commands/rake/rake_command.rb:24:in `block (2 levels) in perform'
/home/travis/build/exec-io/envisage/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
/home/travis/build/exec-io/envisage/vendor/bundle/ruby/2.7.0/gems/railties-7.0.0/lib/rails/commands/rake/rake_command.rb:24:in `block in perform'
/home/travis/build/exec-io/envisage/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/rake_module.rb:59:in `with_application'
/home/travis/build/exec-io/envisage/vendor/bundle/ruby/2.7.0/gems/railties-7.0.0/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/home/travis/build/exec-io/envisage/vendor/bundle/ruby/2.7.0/gems/railties-7.0.0/lib/rails/command.rb:51:in `invoke'
/home/travis/build/exec-io/envisage/vendor/bundle/ruby/2.7.0/gems/railties-7.0.0/lib/rails/commands.rb:18:in `<main>'
/home/travis/build/exec-io/envisage/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/home/travis/build/exec-io/envisage/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
Tasks: TOP => db:create => db:load_config => environment
```

**Comment by tian-im** [comment]
@ryanb thanks, will look into it this weekend

**Comment by ryanb** [comment]
@tian-im I wouldn't spend too much time on it if it's challenging to fix. I just commented out that setting for now and everything is working. Might be nice to restore but it's just a label setting so not critical.

**Comment by tian-im** [comment]
@ryanb it's alright, I have not much to do in weekend anyway XD. Could you update the `wallaby-core` to `0.2.6` and see if it works for you?

**Comment by ryanb** [comment]
@tian-im that seems to have fixed it, thanks!
